#!/usr/bin/env bash
#
# check-hooks-installed.sh — fail loudly when git would run no hooks in this working tree.
#
# Run:  npm run check:hooks
#   (or: bash scripts/check-hooks-installed.sh)
#
# The defect this exists for is SILENCE. `core.hooksPath` is `.husky/_`, and it lives in the
# SHARED .git/config, so every linked worktree inherits it. But `_` is gitignored and
# generated by husky's `prepare` on a ROOT install, so `git worktree add` produces a tree
# where that path names a directory which does not exist. Git runs nothing, says nothing,
# and exits 0. A commit in that window gets no typecheck, no lint-staged, and no formatting,
# and the only evidence is the absence of output, which is exactly what a passing hook also
# looks like.
#
# DELIBERATELY PURE SHELL, DEPENDING ON NOTHING INSTALLED. That is what lets it run in the
# window it exists to catch: `npm run check:hooks` executes the command from package.json
# and needs no dependency tree to do it, so it fails correctly in a worktree with no
# node_modules anywhere. Give it a Node dependency and that property is gone.
#
# It is the first entry in .claude/gauntlet.json and the last gating step of
# scripts/new-worktree.sh, for the same reason.
#
# Read-only: it inspects config and the filesystem and never installs, writes, or repairs.

set -u

fail() {
	printf 'check-hooks-installed: %s\n' "$1" >&2
	printf '\nGit is running NO hooks in this working tree. Fix it with a ROOT install:\n' >&2
	printf '    cd %s && npm install\n' "${ROOT:-<repo root>}" >&2
	printf '\nA per-app install does not help: the prepare script that installs hooks is a ROOT script.\n' >&2
	exit 1
}

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
	echo "check-hooks-installed: not inside a git working tree." >&2
	exit 1
}

hooks_path=$(git config --get core.hooksPath || true)
# Unset means git uses $GIT_DIR/hooks, which for a linked worktree is its own private
# directory that husky never populates. Either way the repo's tracked hooks are not what
# runs, so this is a failure rather than a default worth accepting.
[ -n "$hooks_path" ] || fail "core.hooksPath is unset, so the repo's .husky hooks are not what git runs."

# A relative core.hooksPath resolves against the top of the WORKING TREE, not against
# $GIT_DIR, which is the entire reason a shared config value can be right in one worktree
# and wrong in the next. Resolve it the same way git does.
case "$hooks_path" in
/*) resolved="$hooks_path" ;;
*) resolved="$ROOT/$hooks_path" ;;
esac
[ -d "$resolved" ] || fail "core.hooksPath is '$hooks_path', which resolves to '$resolved' — that directory does not exist."

# Every tracked hook needs an executable dispatcher of the same name under the hooks path,
# or that one hook silently never fires while its neighbors do. Checked per hook rather
# than by counting, so the message can name the missing one.
missing=""
found_any=0
for hook in "$ROOT"/.husky/*; do
	[ -f "$hook" ] || continue
	name=$(basename "$hook")
	found_any=1
	[ -x "$resolved/$name" ] || missing="$missing $name"
done

# A repo with no tracked hooks at all would pass every check above while running nothing.
# The check must not go quiet when its subject disappears.
[ "$found_any" = "1" ] || fail "no tracked hooks found in $ROOT/.husky — nothing would run even if the path resolved."
[ -z "$missing" ] || fail "tracked hook(s) with no dispatcher under '$resolved':$missing"

echo "check-hooks-installed: OK — core.hooksPath '$hooks_path' resolves to '$resolved', and every tracked hook has an executable dispatcher."
