#!/usr/bin/env bash
#
# new-worktree.sh — create a git worktree and provision it so it actually works.
#
# Run:  npm run worktree:new -- <path> <branch> [base-ref]
#   (or: bash scripts/new-worktree.sh ../template.my-feature bryan/my-feature origin/main)
#
# `git worktree add` alone leaves a tree that LOOKS ready and is not, in ways that all fail
# quietly:
#
#   * NO GIT HOOKS. `core.hooksPath` is `.husky/_` and lives in the shared .git/config, so
#     the new worktree inherits it, but `_` is gitignored and generated by husky's `prepare`
#     on a ROOT install. Until that runs, the path names nothing, git runs no hooks, and a
#     commit gets no typecheck, no lint-staged, and no formatting while reporting success.
#   * NO node_modules, in every workspace. A per-app install is not enough: `prepare: husky`
#     is a ROOT script.
#   * NO API BUILD. apps/web's tsconfig maps `@api/*` to apps/api/dist, which no install
#     creates; without a build the typecheck passes and the app fails at runtime.
#   * NO BACKUP OR SPOTLIGHT EXCLUSIONS on the regenerable trees this script itself creates.
#
# So this makes "provisioned" one command rather than a ritual nobody remembers in full. It
# finishes by running check-hooks-installed.sh and FAILS if hooks are still not live; a
# provisioning script that cannot tell you it failed is the same defect one layer up.
#
# It creates and installs. It never deletes a worktree, never touches a branch other than
# the one it creates, and never runs a database or deploy command.

set -u

usage() {
	echo "usage: bash scripts/new-worktree.sh <path> <branch> [base-ref]" >&2
	echo "   e.g. bash scripts/new-worktree.sh ../template.my-feature bryan/my-feature origin/main" >&2
	exit 2
}

[ "$#" -ge 2 ] || usage
target="$1"
branch="$2"
base="${3:-origin/main}"

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
	echo "new-worktree: run this from inside the repo." >&2
	exit 1
}

if [ -e "$target" ]; then
	echo "new-worktree: '$target' already exists — refusing to touch it." >&2
	echo "Provision an EXISTING worktree by running the install steps in it yourself, or pick a new path." >&2
	exit 1
fi

case "$base" in
origin/*)
	echo "new-worktree: fetching $base"
	git fetch origin "${base#origin/}" --quiet ||
		echo "new-worktree: fetch failed; using whatever $base already points at" >&2
	;;
esac

echo "new-worktree: creating $target on $branch (from $base)"
git worktree add -b "$branch" -- "$target" "$base" || exit 1

# Absolute, because every install below runs in a subshell that has cd'd elsewhere.
target_abs=$(cd -- "$target" && pwd) || exit 1

# Every workspace that carries its own package-lock.json. ONE list, because the install loop
# and the exclusion loop below must name the same set. Adding a workspace means adding it
# here; `find . -name package-lock.json -not -path '*/node_modules/*'` regenerates the list.
#
# ROOT FIRST, and that order is load-bearing: the root install is the one that runs
# `prepare: husky` and creates `.husky/_`, so until it finishes the worktree has no hooks.
WORKSPACE_DIRS=(. apps/api apps/web apps/cron)

for dir in "${WORKSPACE_DIRS[@]}"; do
	if [ -f "$target_abs/$dir/package-lock.json" ]; then
		echo "new-worktree: npm ci in $dir"
		# `npm ci` rather than `npm install`: it installs exactly the lockfile and REFUSES
		# when the lockfile and package.json disagree, instead of silently rewriting the
		# file this repo treats as the source of truth for exact versions.
		# </dev/null so a prompt can never hang an unattended run.
		(cd "$target_abs/$dir" && npm ci --no-audit --no-fund </dev/null) || {
			echo "new-worktree: npm ci FAILED in $dir — the worktree is half-provisioned." >&2
			exit 1
		}
	fi
done

echo "new-worktree: building api (apps/web resolves @api/* against apps/api/dist)"
(cd "$target_abs/apps/api" && npm run build) || {
	echo "new-worktree: api build FAILED — apps/web cannot resolve @api/* until it succeeds." >&2
	exit 1
}

# The point of the whole script. If this fails, provisioning did not achieve the thing it
# exists for, and saying so beats printing a success line.
echo "new-worktree: verifying hooks"
(cd "$target_abs" && bash "$ROOT/scripts/check-hooks-installed.sh") || exit 1

# Keep the regenerable trees out of Time Machine and Spotlight. Two SEPARATE mechanisms (a
# backup exclusion does not stop indexing), so both are applied to each path.
#
# `.next` is CREATED EMPTY first so it can be excluded before anything writes to it: the
# tmutil exclusion is an xattr on the directory and survives a build that empties it.
#
# This warns rather than exits: an unexcluded tree is a disk-hygiene problem, not a broken
# one. Non-macOS has no tmutil, so the backup half is skipped there.
exclude_tree() {
	# $1 = absolute path to a directory that should be neither backed up nor indexed.
	[ -d "$1" ] || return 0
	touch "$1/.metadata_never_index" 2>/dev/null ||
		echo "new-worktree: WARNING could not write $1/.metadata_never_index (Spotlight will index it)" >&2
	if command -v tmutil >/dev/null 2>&1; then
		tmutil addexclusion "$1" >/dev/null 2>&1 ||
			echo "new-worktree: WARNING tmutil addexclusion failed for $1 (Time Machine will back it up)" >&2
	fi
}

echo "new-worktree: excluding regenerable trees from backup and indexing"
mkdir -p "$target_abs/apps/web/.next" ||
	echo "new-worktree: WARNING could not create apps/web/.next — it will be indexed and backed up once a build creates it" >&2
for dir in "${WORKSPACE_DIRS[@]}"; do
	exclude_tree "$target_abs/$dir/node_modules"
done
exclude_tree "$target_abs/apps/web/.next"
exclude_tree "$target_abs/apps/api/dist"

echo
echo "new-worktree: ready — $target_abs"
echo "  Not copied, deliberately: gitignored env files (apps/api/.env, apps/web/.env.local)."
echo "  They hold real credentials, so copy them yourself if this worktree needs to run the app."
